// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AgentRun struct {
	ID            string               `json:"id"`
	Status        AgentRunStatus       `json:"status"`
	Mode          AgentMode            `json:"mode"`
	Provider      ModelProvider        `json:"provider"`
	FeedbackCount int32                `json:"feedbackCount"`
	Results       []*FeedbackResult    `json:"results"`
	Tasks         []*InvestigationTask `json:"tasks"`
	StartedAt     string               `json:"startedAt"`
	CompletedAt   *string              `json:"completedAt,omitempty"`
	ErrorMessage  *string              `json:"errorMessage,omitempty"`
}

type Classification struct {
	Topic                 Topic  `json:"topic"`
	Severity              int32  `json:"severity"`
	Evidence              string `json:"evidence"`
	RequiresInvestigation bool   `json:"requiresInvestigation"`
	EvidenceValid         bool   `json:"evidenceValid"`
}

type FeedbackInput struct {
	FeedbackID   string         `json:"feedbackId"`
	FeedbackText string         `json:"feedbackText"`
	Product      string         `json:"product"`
	Source       string         `json:"source"`
	OccurredAt   string         `json:"occurredAt"`
	Period       FeedbackPeriod `json:"period"`
}

type FeedbackResult struct {
	FeedbackID     string          `json:"feedbackId"`
	FeedbackText   string          `json:"feedbackText"`
	Product        string          `json:"product"`
	Source         string          `json:"source"`
	OccurredAt     string          `json:"occurredAt"`
	Period         FeedbackPeriod  `json:"period"`
	Classification *Classification `json:"classification"`
}

type Health struct {
	Status  string `json:"status"`
	Service string `json:"service"`
	Version string `json:"version"`
}

type InvestigationMetrics struct {
	CurrentIssueMessages    int32    `json:"currentIssueMessages"`
	CurrentProductMessages  int32    `json:"currentProductMessages"`
	CurrentSharePercentage  float64  `json:"currentSharePercentage"`
	PreviousIssueMessages   int32    `json:"previousIssueMessages"`
	PreviousProductMessages int32    `json:"previousProductMessages"`
	PreviousSharePercentage *float64 `json:"previousSharePercentage,omitempty"`
	ChangePercentagePoints  *float64 `json:"changePercentagePoints,omitempty"`
	ComparisonStatus        string   `json:"comparisonStatus"`
}

type InvestigationTask struct {
	ID                 string                `json:"id"`
	TaskKey            string                `json:"taskKey"`
	Title              string                `json:"title"`
	Product            string                `json:"product"`
	Topic              Topic                 `json:"topic"`
	Priority           Priority              `json:"priority"`
	Status             TaskStatus            `json:"status"`
	Reason             string                `json:"reason"`
	Metrics            *InvestigationMetrics `json:"metrics"`
	SupportingEvidence []*SupportingEvidence `json:"supportingEvidence"`
	RecommendedAction  string                `json:"recommendedAction"`
	Urgent             bool                  `json:"urgent"`
	UrgentReason       string                `json:"urgentReason"`
	CreatedAt          string                `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type RunInvestigationInput struct {
	Feedback []*FeedbackInput `json:"feedback"`
	Mode     AgentMode        `json:"mode"`
	Provider ModelProvider    `json:"provider"`
}

type SupportingEvidence struct {
	FeedbackID string `json:"feedbackId"`
	Text       string `json:"text"`
}

type AgentMode string

const (
	AgentModeDemo AgentMode = "DEMO"
	AgentModeLive AgentMode = "LIVE"
)

var AllAgentMode = []AgentMode{
	AgentModeDemo,
	AgentModeLive,
}

func (e AgentMode) IsValid() bool {
	switch e {
	case AgentModeDemo, AgentModeLive:
		return true
	}
	return false
}

func (e AgentMode) String() string {
	return string(e)
}

func (e *AgentMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMode", str)
	}
	return nil
}

func (e AgentMode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentRunStatus string

const (
	AgentRunStatusPending   AgentRunStatus = "PENDING"
	AgentRunStatusRunning   AgentRunStatus = "RUNNING"
	AgentRunStatusCompleted AgentRunStatus = "COMPLETED"
	AgentRunStatusFailed    AgentRunStatus = "FAILED"
)

var AllAgentRunStatus = []AgentRunStatus{
	AgentRunStatusPending,
	AgentRunStatusRunning,
	AgentRunStatusCompleted,
	AgentRunStatusFailed,
}

func (e AgentRunStatus) IsValid() bool {
	switch e {
	case AgentRunStatusPending, AgentRunStatusRunning, AgentRunStatusCompleted, AgentRunStatusFailed:
		return true
	}
	return false
}

func (e AgentRunStatus) String() string {
	return string(e)
}

func (e *AgentRunStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentRunStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentRunStatus", str)
	}
	return nil
}

func (e AgentRunStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentRunStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentRunStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FeedbackPeriod string

const (
	FeedbackPeriodCurrent  FeedbackPeriod = "CURRENT"
	FeedbackPeriodPrevious FeedbackPeriod = "PREVIOUS"
)

var AllFeedbackPeriod = []FeedbackPeriod{
	FeedbackPeriodCurrent,
	FeedbackPeriodPrevious,
}

func (e FeedbackPeriod) IsValid() bool {
	switch e {
	case FeedbackPeriodCurrent, FeedbackPeriodPrevious:
		return true
	}
	return false
}

func (e FeedbackPeriod) String() string {
	return string(e)
}

func (e *FeedbackPeriod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FeedbackPeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FeedbackPeriod", str)
	}
	return nil
}

func (e FeedbackPeriod) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FeedbackPeriod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FeedbackPeriod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ModelProvider string

const (
	ModelProviderDemo      ModelProvider = "DEMO"
	ModelProviderOpenai    ModelProvider = "OPENAI"
	ModelProviderAnthropic ModelProvider = "ANTHROPIC"
	ModelProviderGrok      ModelProvider = "GROK"
	ModelProviderOllama    ModelProvider = "OLLAMA"
)

var AllModelProvider = []ModelProvider{
	ModelProviderDemo,
	ModelProviderOpenai,
	ModelProviderAnthropic,
	ModelProviderGrok,
	ModelProviderOllama,
}

func (e ModelProvider) IsValid() bool {
	switch e {
	case ModelProviderDemo, ModelProviderOpenai, ModelProviderAnthropic, ModelProviderGrok, ModelProviderOllama:
		return true
	}
	return false
}

func (e ModelProvider) String() string {
	return string(e)
}

func (e *ModelProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ModelProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ModelProvider", str)
	}
	return nil
}

func (e ModelProvider) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ModelProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ModelProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Priority string

const (
	PriorityLow      Priority = "LOW"
	PriorityMedium   Priority = "MEDIUM"
	PriorityHigh     Priority = "HIGH"
	PriorityCritical Priority = "CRITICAL"
)

var AllPriority = []Priority{
	PriorityLow,
	PriorityMedium,
	PriorityHigh,
	PriorityCritical,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityLow, PriorityMedium, PriorityHigh, PriorityCritical:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Priority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Priority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TaskStatus string

const (
	TaskStatusOpen       TaskStatus = "OPEN"
	TaskStatusInProgress TaskStatus = "IN_PROGRESS"
	TaskStatusResolved   TaskStatus = "RESOLVED"
	TaskStatusDismissed  TaskStatus = "DISMISSED"
)

var AllTaskStatus = []TaskStatus{
	TaskStatusOpen,
	TaskStatusInProgress,
	TaskStatusResolved,
	TaskStatusDismissed,
}

func (e TaskStatus) IsValid() bool {
	switch e {
	case TaskStatusOpen, TaskStatusInProgress, TaskStatusResolved, TaskStatusDismissed:
		return true
	}
	return false
}

func (e TaskStatus) String() string {
	return string(e)
}

func (e *TaskStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TaskStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TaskStatus", str)
	}
	return nil
}

func (e TaskStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TaskStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TaskStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Topic string

const (
	TopicDeliveryDelay    Topic = "DELIVERY_DELAY"
	TopicDamagedPackaging Topic = "DAMAGED_PACKAGING"
	TopicPrintQuality     Topic = "PRINT_QUALITY"
	TopicAdhesion         Topic = "ADHESION"
	TopicArtworkProcess   Topic = "ARTWORK_PROCESS"
	TopicOther            Topic = "OTHER"
	TopicPositive         Topic = "POSITIVE"
	TopicNeutral          Topic = "NEUTRAL"
)

var AllTopic = []Topic{
	TopicDeliveryDelay,
	TopicDamagedPackaging,
	TopicPrintQuality,
	TopicAdhesion,
	TopicArtworkProcess,
	TopicOther,
	TopicPositive,
	TopicNeutral,
}

func (e Topic) IsValid() bool {
	switch e {
	case TopicDeliveryDelay, TopicDamagedPackaging, TopicPrintQuality, TopicAdhesion, TopicArtworkProcess, TopicOther, TopicPositive, TopicNeutral:
		return true
	}
	return false
}

func (e Topic) String() string {
	return string(e)
}

func (e *Topic) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Topic(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Topic", str)
	}
	return nil
}

func (e Topic) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Topic) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Topic) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
